/** Action Constants for utils */
export const CHANGE_TAB = 'CHANGE_TAB';

export const NOTIFICATION_TIME_SHORT = 1000;
export const NOTIFICATION_TIME_MEDIUM = 3000;
export const NOTIFICATION_TIME_LONG = 5000;

/** Action Constants for All Cases */
export const FETCH_COVID_DATA_PENDING = 'FETCH_COVID_DATA_PENDING';
export const FETCH_COVID_DATA_SUCCESS = 'FETCH_COVID_DATA_SUCCESS';
export const FETCH_COVID_DATA_FAILED = 'FETCH_COVID_DATA_FAILED';

/** Action Constants for Onatrio Recent cases */
export const FETCH_ONTARIO_RECENT_DATA_PENDING = 'FETCH_ONTARIO_RECENT_DATA_PENDING';
export const FETCH_ONTARIO_RECENT_DATA_SUCCESS = 'FETCH_ONTARIO_RECENT_DATA_SUCCESS';
export const FETCH_ONTARIO_RECENT_DATA_FAILED = 'FETCH_ONTARIO_RECENT_DATA_FAILED';